'use client'

import { useMemo, useState } from 'react'
import { ArrowLeft, CalendarDays, ChevronDown, ChevronLeft, ChevronRight, MoreHorizontal, Package, Plus, Search, ShoppingBag, Users, WalletCards, X } from 'lucide-react'

type Payment = 'Efectivo' | 'Transferencia' | 'Tarjeta'
type Sale = { id: number; date: string; client: string; phone: string; products: string[]; payment: Payment; total: number }

const sales: Sale[] = [
  { id: 42, date: '14/05/2024', client: 'Marina Costa', phone: '+54 9 11 5555-0182', products: ['Elfbar 5000', 'Pods Vuse'], payment: 'Transferencia', total: 89580 },
  { id: 41, date: '11/05/2024', client: 'Rafael Mendes', phone: '+54 9 11 5555-1430', products: ['Blue Razz Ice'], payment: 'Efectivo', total: 32900 },
  { id: 40, date: '08/05/2024', client: 'Bianca Nunes', phone: '+54 9 11 5555-2291', products: ['Elfbar 5000', 'Lemon Mint'], payment: 'Tarjeta', total: 67400 },
  { id: 39, date: '30/04/2024', client: 'Lucas Almeida', phone: '+54 9 11 5555-3902', products: ['Vuse Go 5000'], payment: 'Transferencia', total: 28500 },
  { id: 38, date: '25/04/2024', client: 'Sofía Romero', phone: '+54 9 11 5555-4450', products: ['Grape Ice', 'Strawberry Kiwi'], payment: 'Efectivo', total: 51200 },
  { id: 37, date: '19/04/2024', client: 'Tomás Herrera', phone: '+54 9 11 5555-5599', products: ['Elfbar 5000'], payment: 'Tarjeta', total: 39800 },
  { id: 36, date: '12/04/2024', client: 'Carla Benítez', phone: '+54 9 11 5555-6133', products: ['Blue Razz Ice', 'Pods Vuse'], payment: 'Transferencia', total: 64700 },
  { id: 35, date: '03/04/2024', client: 'Nicolás Suárez', phone: '+54 9 11 5555-7021', products: ['Lemon Mint'], payment: 'Efectivo', total: 24900 },
  { id: 34, date: '27/03/2024', client: 'Valentina Díaz', phone: '+54 9 11 5555-8110', products: ['Vuse Go 5000', 'Grape Ice'], payment: 'Tarjeta', total: 59800 },
  { id: 33, date: '18/03/2024', client: 'Martín Acosta', phone: '+54 9 11 5555-9345', products: ['Strawberry Kiwi'], payment: 'Transferencia', total: 27900 },
  { id: 32, date: '09/03/2024', client: 'Julia Paz', phone: '+54 9 11 5555-1044', products: ['Elfbar 5000'], payment: 'Efectivo', total: 39800 },
  { id: 31, date: '26/02/2024', client: 'Franco Molina', phone: '+54 9 11 5555-1188', products: ['Pods Vuse', 'Lemon Mint'], payment: 'Tarjeta', total: 47600 },
  { id: 30, date: '14/02/2024', client: 'Agustina Vega', phone: '+54 9 11 5555-2234', products: ['Blue Razz Ice'], payment: 'Transferencia', total: 32900 },
  { id: 29, date: '02/02/2024', client: 'Diego Torres', phone: '+54 9 11 5555-3319', products: ['Grape Ice'], payment: 'Efectivo', total: 29900 },
  { id: 28, date: '25/01/2024', client: 'Camila Ríos', phone: '+54 9 11 5555-4491', products: ['Vuse Go 5000'], payment: 'Tarjeta', total: 28500 },
]
const products = [{ name: 'Elfbar 5000', brand: 'Elfbar', price: 39800 }, { name: 'Blue Razz Ice', brand: 'Elfbar', price: 32900 }, { name: 'Lemon Mint', brand: 'Vuse', price: 24900 }, { name: 'Pods Vuse', brand: 'Vuse', price: 27900 }]
const money = (n: number) => `$ ${n.toLocaleString('es-AR')}`

export default function Page() {
  const [view, setView] = useState<'Ventas' | 'Detalle'>('Ventas')
  const [query, setQuery] = useState('')
  const [payment, setPayment] = useState('Todos')
  const [showNew, setShowNew] = useState(false)
  const [selected, setSelected] = useState<Sale | null>(null)
  const [menu, setMenu] = useState<number | null>(null)
  const filtered = useMemo(() => sales.filter(s => s.client.toLowerCase().includes(query.toLowerCase()) && (payment === 'Todos' || s.payment === payment)), [query, payment])

  if (view === 'Detalle' && selected) return <Detail sale={selected} onBack={() => setView('Ventas')} />
  return <main className="app-shell"><Sidebar active="Ventas" /><section className="main-content"><header className="topbar"><div className="breadcrumbs"><span>Glauss Shop</span><span>/</span><strong>Ventas</strong></div><div className="top-actions"><button className="icon-button" aria-label="Buscar"><Search /></button><button className="icon-button" aria-label="Notificaciones">●</button><button className="quick-button" onClick={() => setShowNew(true)}><Plus /> Nueva venta</button></div></header><div className="content-wrap sales-page"><div className="page-heading sales-heading"><div><p className="eyebrow">OPERACIONES</p><h1>Ventas</h1><p className="heading-subtitle">Registrá y consultá todas las ventas de tu tienda.</p></div><button className="quick-button" onClick={() => setShowNew(true)}><Plus /> Nueva venta</button></div><div className="sales-filters"><div className="filter-control"><CalendarDays /><span>01/01/2024 — 14/05/2024</span><ChevronDown /></div><div className="filter-control"><WalletCards /><select value={payment} onChange={e => setPayment(e.target.value)}><option>Todos</option><option>Efectivo</option><option>Transferencia</option><option>Tarjeta</option></select><ChevronDown /></div><label className="search-control"><Search /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Buscar por cliente..." /></label></div><div className="card sales-table-card"><div className="sales-table-top"><div><h2>Historial de ventas</h2><p>{filtered.length} ventas encontradas</p></div><span className="table-total">Total del período <strong>{money(filtered.reduce((a, s) => a + s.total, 0))}</strong></span></div><div className="sales-table-wrap"><table><thead><tr><th>N°</th><th>Fecha</th><th>Cliente</th><th>Productos</th><th>Método de pago</th><th>Total</th><th /></tr></thead><tbody>{filtered.map(s => <tr key={s.id}><td className="sale-number">{String(s.id).padStart(4, '0')}</td><td>{s.date}</td><td><div className="client-table"><span>{s.client.split(' ').map(x => x[0]).join('')}</span><strong>{s.client}</strong></div></td><td><span className="product-summary">{s.products[0]}{s.products.length > 1 ? ` + ${s.products.length - 1} más` : ''}</span></td><td><PaymentPill payment={s.payment} /></td><td><strong>{money(s.total)}</strong></td><td className="action-cell"><button aria-label="Acciones" onClick={() => setMenu(menu === s.id ? null : s.id)}><MoreHorizontal /></button>{menu === s.id && <div className="row-menu"><button onClick={() => { setSelected(s); setView('Detalle'); setMenu(null) }}>Ver detalle</button><button onClick={() => setMenu(null)}>Eliminar</button></div>}</td></tr>)}</tbody></table></div><div className="pagination"><span>Mostrando 1-15 de 15 ventas</span><div><button disabled><ChevronLeft /></button><button className="current-page">1</button><button disabled><ChevronRight /></button></div></div></div></div></section>{showNew && <NewSale onClose={() => setShowNew(false)} />}</main>
}

function Sidebar({ active }: { active: string }) { return <aside className="sidebar"><div className="brand"><span className="brand-mark">g</span><span>glauss</span><span className="brand-dot">.</span></div><div className="workspace"><div className="workspace-avatar">GS</div><div><strong>Glauss Shop</strong><span>Mi tienda</span></div><ChevronDown /></div><nav className="nav-list"><span className="nav-label">MENU PRINCIPAL</span>{[['Resumen', '◈'], ['Ventas', '▣'], ['Clientes', '♙'], ['Productos y stock', '□'], ['Finanzas', '$'], ['Reportes', '▤']].map(([label, icon]) => <button key={label} className={`nav-item ${label === active ? 'active' : ''}`}><span className="nav-glyph">{icon}</span>{label}{label === 'Clientes' && <span className="nav-count">12</span>}</button>)}</nav><div className="sidebar-bottom"><div className="upgrade-card"><div className="upgrade-icon">✦</div><strong>Desbloqueá todo el potencial</strong><p>Tené reportes avanzados y mucho más.</p><button>Conocer plan Pro →</button></div><button className="nav-item">? <span>Central de ayuda</span></button><button className="nav-item">⚙ <span>Configuración</span></button><div className="profile"><div className="profile-avatar">JS</div><div><strong>João Silva</strong><span>Administrador</span></div><MoreHorizontal /></div></div></aside> }
function PaymentPill({ payment }: { payment: Payment }) { return <span className={`payment-pill ${payment.toLowerCase()}`}>{payment}</span> }

function NewSale({ onClose }: { onClose: () => void }) { const [client, setClient] = useState(''); const [items, setItems] = useState([{ ...products[0], qty: 1 }]); const [method, setMethod] = useState<Payment>('Efectivo'); const total = items.reduce((a, p) => a + p.price * p.qty, 0); return <div className="modal-backdrop"><section className="sale-modal" role="dialog" aria-modal="true"><header><div><p className="eyebrow">NUEVA OPERACIÓN</p><h2>Nueva venta</h2></div><button className="close-button" onClick={onClose}><X /></button></header><div className="modal-body"><label className="field"><span>Cliente</span><div className="field-input"><Users /><input value={client} onChange={e => setClient(e.target.value)} placeholder="Buscar cliente existente..." /><ChevronDown /></div><button className="create-link">+ Crear cliente nuevo</button></label><div className="field"><span>Productos</span><div className="field-input"><Search /><input placeholder="Buscar producto para agregar..." /></div></div><div className="sale-items">{items.map((p, i) => <div className="sale-item" key={p.name}><div className="item-icon"><Package /></div><div className="item-info"><strong>{p.name}</strong><small>{p.brand} · {money(p.price)}</small></div><div className="qty"><button onClick={() => setItems(items.map((x, j) => j === i ? { ...x, qty: Math.max(1, x.qty - 1) } : x))}>−</button><strong>{p.qty}</strong><button onClick={() => setItems(items.map((x, j) => j === i ? { ...x, qty: x.qty + 1 } : x))}>+</button></div><strong>{money(p.price * p.qty)}</strong><button className="remove-item" onClick={() => setItems(items.filter((_, j) => j !== i))}><X /></button></div>)}</div><button className="add-product" onClick={() => setItems([...items, { ...products[1], qty: 1 }])}><Plus /> Agregar otro producto</button><div className="modal-fields"><label className="field"><span>Método de pago</span><select value={method} onChange={e => setMethod(e.target.value as Payment)}><option>Efectivo</option><option>Transferencia</option><option>Tarjeta</option></select></label><label className="field"><span>Fecha</span><input type="date" defaultValue="2024-05-14" /></label></div></div><footer><button className="cancel-button" onClick={onClose}>Cancelar</button><div className="modal-total"><span>Total de la venta</span><strong>{money(total)}</strong></div><button className="quick-button" onClick={onClose}>Registrar venta</button></footer></section></div> }

function Detail({ sale, onBack }: { sale: Sale; onBack: () => void }) { return <main className="app-shell"><Sidebar active="Ventas" /><section className="main-content"><header className="topbar"><div className="breadcrumbs"><span>Glauss Shop</span><span>/</span><strong>Detalle de venta</strong></div></header><div className="content-wrap detail-page"><button className="back-link" onClick={onBack}><ArrowLeft /> Volver a ventas</button><div className="detail-heading"><div><p className="eyebrow">DETALLE DE OPERACIÓN</p><h1>Venta N° {String(sale.id).padStart(4, '0')}</h1><p className="heading-subtitle">Registrada el {sale.date}</p></div><PaymentPill payment={sale.payment} /></div><div className="card customer-detail"><div className="big-avatar">{sale.client.split(' ').map(x => x[0]).join('')}</div><div><p className="eyebrow">CLIENTE</p><h2>{sale.client}</h2><p>{sale.phone}</p></div><a className="whatsapp-button" href={`https://wa.me/${sale.phone.replace(/\D/g, '')}`} target="_blank">WhatsApp</a></div><div className="card detail-items"><h2>Productos de la venta</h2><table><thead><tr><th>Producto</th><th>Marca</th><th>Cantidad</th><th>Precio unitario</th><th>Subtotal</th></tr></thead><tbody>{sale.products.map((p, i) => <tr key={p}><td><strong>{p}</strong></td><td>Elfbar</td><td>1</td><td>{money(i ? 27900 : sale.total - (sale.products.length - 1) * 27900)}</td><td><strong>{money(i ? 27900 : sale.total - (sale.products.length - 1) * 27900)}</strong></td></tr>)}</tbody></table><div className="detail-total"><span>Total</span><strong>{money(sale.total)}</strong></div></div></div></section></main> }
